# Generated by Django 3.2.9 on 2021-12-05 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbliometrics', '0002_prova'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prova',
            new_name='Authors_Group',
        ),
    ]
