# Generated by Django 3.2.9 on 2021-12-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbliometrics', '0004_auto_20211205_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorsgroup',
            name='other_info',
            field=models.TextField(max_length=200),
        ),
    ]
