# Generated by Django 3.2.9 on 2021-12-06 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbliometrics', '0005_alter_authorsgroup_other_info'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authorsgroup',
            table='AuthorsGroups',
        ),
    ]
