# Generated by Django 3.2.9 on 2021-12-06 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbliometrics', '0006_alter_authorsgroup_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authorsgroup',
            table='Agroups',
        ),
    ]
