# Generated by Django 3.2.9 on 2021-12-06 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbliometrics', '0007_alter_authorsgroup_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorsGroup',
            new_name='Agroup',
        ),
    ]
