# Generated by Django 3.2.9 on 2021-12-06 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbliometrics', '0008_rename_authorsgroup_agroup'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agroup',
            table=None,
        ),
    ]
