# Generated by Django 3.2.9 on 2021-12-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbliometrics', '0009_alter_agroup_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopusId', models.PositiveBigIntegerField(unique=True)),
                ('name', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=50)),
                ('city', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=50)),
                ('postal_code', models.TextField(max_length=50)),
                ('country', models.TextField(max_length=50)),
                ('url', models.URLField()),
                ('creation', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
    ]
