# Generated by Django 3.2.9 on 2021-12-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbliometrics', '0010_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='name',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
