# Generated by Django 3.2.9 on 2021-12-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbliometrics', '0012_auto_20211209_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agroup',
            name='other_info',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
