# Generated by Django 3.2.9 on 2021-12-09 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gbliometrics', '0013_auto_20211209_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopusId', models.PositiveBigIntegerField(unique=True)),
                ('orcid', models.PositiveBigIntegerField(unique=True)),
                ('name', models.TextField(max_length=50)),
                ('surname', models.TextField(max_length=50)),
                ('full_name', models.TextField(max_length=100)),
                ('creation', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gbliometrics.affiliation')),
            ],
        ),
    ]
