# Generated by Django 3.2.9 on 2021-12-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbliometrics', '0016_auto_20211210_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='orcid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
