# Generated by Django 3.2.9 on 2021-12-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbliometrics', '0018_auto_20211210_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='creation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='last_update',
            field=models.DateTimeField(),
        ),
    ]
