# Generated by Django 3.2.9 on 2021-12-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbliometrics', '0020_alter_author_orcid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='orcid',
        ),
    ]
