# Generated by Django 3.2.9 on 2021-12-12 23:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gbliometrics.models


class Migration(migrations.Migration):

    dependencies = [
        ('gbliometrics', '0023_auto_20211212_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('creation', models.DateTimeField(default=datetime.datetime(2021, 12, 13, 0, 32, 53, 401124))),
                ('informations', models.FileField(upload_to=gbliometrics.models.Snapshot.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        )
    ]
